const films = [
    { titre: "300", video: "https://www.youtube.com/watch?v=YNTY7tnmsxY&t=36s", image: "images/300.jpg", acteurs: "Gerard Butler, Lena Headey", genres: ["Action", "Guerre"] },
    { titre: "2012", video: "https://www.youtube.com/watch?v=m33rzUxflto&t=25s", image: "images/2012.jpg", acteurs: "John Cusack, Chiwetel Ejiofor, Amanda Peet", genres: ["Science-fiction", "Catastrophe"] },
    { titre: "24_heure_limit", video: "https://www.youtube.com/watch?v=zrCb5klZZCc", image: "images/24_heure_limit.jpg", acteurs: "Ethan Hawke", genres: ["Thriller", "Action"] },
    { titre: "50_nuances_de_grey", video: "https://www.youtube.com/watch?v=9G7oSGWHSVc&t=49s", image: "images/50_nuances_de_grey.jpg", acteurs: "Dakota Johnson, Jamie Dornan", genres: ["Romance", "Drame"] },
    { titre: "50_nuances_plus_claire", video: "https://www.youtube.com/watch?v=p-2dGdfZzL4", image: "images/50_nuances_plus_claire.jpg", acteurs: "Dakota Johnson, Jamie Dornan", genres: ["Romance", "Drame"] },
    { titre: "50_nuances_plus_sombre", video: "https://www.youtube.com/watch?v=0Ah1o0ZZjNY", image: "images/50_nuances_plus_sombre.jpg", acteurs: "Dakota Johnson, Jamie Dornan", genres: ["Romance", "Drame"] },
    { titre: "60_secondes_chrono", video: "https://www.youtube.com/watch?v=uhg-Y93I9-A", image: "images/60_secondes_chrono.jpg", acteurs: "", genres: ["Action"] },
    { titre: "a_star_is_born", video: "https://www.youtube.com/watch?v=jsg9NxCBzFs&t=31s", image: "images/a_star_is_born.jpg", acteurs: "Bradley Cooper, Lady Gaga", genres: ["Musical", "Drame"] },
    { titre: "ad_astra", video: "https://www.youtube.com/watch?v=Gf97Szc_UfI", image: "images/ad_astra.jpg", acteurs: "", genres: ["Science-fiction"] },
    { titre: "aladdin", video: "https://www.youtube.com/watch?v=IrzzGm3AmLg&t=31s", image: "images/aladdin.jpg", acteurs: "Mena Massoud, Naomi Scott", genres: ["Aventure"] },
    { titre: "alibi_com", video: "https://www.youtube.com/watch?v=7jniyVsrfv8", image: "images/alibi_com.jpg", acteurs: "Philippe Lacheau, Élodie Fontan", genres: ["Comédie"] },
    { titre: "aliens_1", video: "https://www.youtube.com/watch?v=j3CFj1R9HbQ&t=35s", image: "images/aliens_1.jpg", acteurs: "Sigourney Weaver", genres: ["Horreur", "Science-fiction"] },
    { titre: "aliens_2", video: "https://www.youtube.com/watch?v=gaJFi3LiFOQ&t=25s", image: "images/aliens_2.jpg", acteurs: "Sigourney Weaver, Michael Biehn", genres: ["Horreur", "Science-fiction"] },
    { titre: "aliens_3", video: "https://www.youtube.com/watch?v=qL-NR79zS7A", image: "images/aliens_3.jpg", acteurs: "Sigourney Weaver, Charles S. Dutton", genres: ["Horreur", "Science-fiction"] },
    { titre: "aliens_4", video: "https://www.youtube.com/watch?v=JMpSSEWoqWA&t=25s", image: "images/aliens_4.jpg", acteurs: "", genres: ["Horreur", "Science-fiction"] },
    { titre: "aliens_5", video: "https://www.youtube.com/watch?v=o_rfh8wBnGE", image: "images/aliens_5.jpg", acteurs: "Sigourney Weaver, Winona Ryder", genres: ["Horreur", "Science-fiction"] },
    { titre: "aliens_6_prometeus", video: "https://www.youtube.com/watch?v=Oxv5SP3sags&t=53s", image: "images/aliens_6_prometeus.jpg", acteurs: "Noomi Rapace, Michael Fassbender", genres: ["Horreur", "Science-fiction"] },
    { titre: "alita", video: "https://www.youtube.com/watch?v=c4nJBG8xB7s", image: "images/alita.jpg", acteurs: "Rosa Salazar, Christoph Waltz", genres: ["Science-fiction"] },
    { titre: "amercican_nigthmare_1", video: "https://www.youtube.com/watch?v=AVRk-UhPkHU", image: "images/amercican_nigthmare_1.jpg", acteurs: "Ethan Hawke, Lena Headey", genres: ["Horreur", "Action"] },
    { titre: "amercican_nigthmare_2", video: "https://www.youtube.com/watch?v=tpNKIBt-pXA", image: "images/amercican_nigthmare_2.jpg", acteurs: "Frank Grillo, Carmen Ejogo", genres: ["Horreur", "Action"] },
    { titre: "amercican_nigthmare_3", video: "https://www.youtube.com/watch?v=FW8CqyN7esE", image: "images/amercican_nigthmare_3.jpg", acteurs: "Frank Grillo, Elizabeth Mitchell", genres: ["Horreur", "Action"] },
    { titre: "amercican_nigthmare_4", video: "https://www.youtube.com/watch?v=O6_CqoAT2bM", image: "images/amercican_nigthmare_4.jpg", acteurs: "Y'lan Noel, Lex Scott Davis", genres: ["Horreur", "Action"] },
    { titre: "anges_et_demons", video: "https://www.youtube.com/watch?v=6fvLICEn4RI&t=1s", image: "images/anges_et_demons.jpg", acteurs: "Tom Hanks, Ewan McGregor", genres: ["Thriller", "Mystère"] },
    { titre: "annabelle", video: "https://www.youtube.com/watch?v=LUCOp6efZmg&t=35s", image: "images/annabelle.jpg", acteurs: "Annabelle Wallis, Ward Horton", genres: ["Horreur"] },
    { titre: "annabelle_2", video: "https://www.youtube.com/watch?v=WOWrsTwxU48", image: "images/annabelle_2.jpg", acteurs: "Stephanie Sigman, Miranda Otto", genres: ["Horreur"] },
    { titre: "ant_man_1", video: "https://www.youtube.com/watch?v=_mWjqYXA59E", image: "images/ant_man_1.jpg", acteurs: "Paul Rudd, Michael Douglas, Evangeline Lilly", genres: ["Action", "Comédie"] },
    { titre: "ant_man_et_la_guepe", video: "https://www.youtube.com/watch?v=Ar38xc7JWxc", image: "images/ant_man_et_la_guepe.jpg", acteurs: "Paul Rudd, Evangeline Lilly, Michael Douglas", genres: ["Action", "Comédie"] },
    { titre: "ant_man_quantumania", video: "https://www.youtube.com/watch?v=Q0uaHT1wsTQ", image: "images/ant_man_quantumania.jpg", acteurs: "Paul Rudd, Evangeline Lilly, Jonathan Majors", genres: ["Action", "Comédie"] },
    { titre: "aquaman", video: "https://www.youtube.com/watch?v=ivvOKs7B-Vw", image: "images/aquaman.jpg", acteurs: "Jason Momoa, Amber Heard", genres: ["Action"] },
    { titre: "armageddon", video: "https://www.youtube.com/watch?v=cYznwIfEFFg&t=25s", image: "images/armageddon.jpg", acteurs: "Bruce Willis, Ben Affleck, Liv Tyler", genres: ["Action", "Science-fiction"] },
    { titre: "arthur_et_les_minimoys", video: "https://www.youtube.com/watch?v=qJeKKd0gPiU&t=22s", image: "images/arthur_et_les_minimoys.jpg", acteurs: "Freddie Highmore, Mia Farrow (voix)", genres: ["Aventure", "Comédie"] },
    { titre: "arthur_et_les_minimoys_2", video: "https://www.youtube.com/watch?v=jgCFy7kl9T8&t=43s", image: "images/arthur_et_les_minimoys_2.jpg", acteurs: "Freddie Highmore, Selena Gomez (voix)", genres: ["Aventure", "Comédie"] },
    { titre: "arthur_et_les_minimoys_3", video: "https://www.youtube.com/watch?v=mOdxATJwad0&t=37s", image: "images/arthur_et_les_minimoys_3.jpg", acteurs: "Freddie Highmore, Mia Farrow (voix)", genres: ["Aventure", "Comédie"] },
    { titre: "asterix_et_obelix", video: "https://www.youtube.com/watch?v=RNKFKDs5SGk&t=46s", image: "images/asterix_et_obelix.jpg", acteurs: "", genres: ["Aventure", "Comédie"] },
    { titre: "avatar_1", video: "https://www.youtube.com/watch?v=O1CzgULNRGs", image: "images/avatar_1.jpg", acteurs: "Sam Worthington, Zoe Saldana", genres: ["Science-fiction", "Action"] },
    { titre: "avatar_2", video: "https://www.youtube.com/watch?v=598NnroP42s", image: "images/avatar_2.jpg", acteurs: "Sam Worthington, Zoe Saldana", genres: ["Science-fiction", "Action"] },
    { titre: "avengers_1", video: "https://www.youtube.com/watch?v=b-kTeJhHOhc&t=40s", image: "images/avengers_1.jpg", acteurs: "Robert Downey Jr., Chris Evans, Mark Ruffalo", genres: ["Action"] },
    { titre: "avengers_4_endgame", video: "https://www.youtube.com/watch?v=wV-Q0o2OQjQ&t=55s", image: "images/avengers_endgame.jpg", acteurs: "Robert Downey Jr., Chris Evans, Mark Ruffalo", genres: ["Action"] },
    { titre: "avengers_3_infinity_war", video: "https://www.youtube.com/watch?v=UDW_LLdERFw", image: "images/avengers_infinity_war.jpg", acteurs: "Robert Downey Jr., Chris Evans, Scarlett Johansson", genres: ["Action"] },
    { titre: "avengers_2_l_ere_d_ultron", video: "https://www.youtube.com/watch?v=XmzJ5WMSr-g", image: "images/avengers_lere_dultron.jpg", acteurs: "Robert Downey Jr., Chris Evans, Scarlett Johansson", genres: ["Action"] },
    { titre: "batman_the_darknight", video: "https://www.youtube.com/watch?v=UMgb3hQCb08", image: "images/batman_the_darknight.jpg", acteurs: "Christian Bale, Heath Ledger", genres: ["Action", "Science-fiction"] },
    { titre: "batman_vs_superman", video: "https://www.youtube.com/watch?v=rW4ZaR2Jndg&t=37s", image: "images/batman_vs_superman.jpg", acteurs: "Ben Affleck, Henry Cavill", genres: ["Action", "Science-fiction"] },
    { titre: "bird_of_prey", video: "https://www.youtube.com/watch?v=6bh1OHkIuYA", image: "images/bird_of_prey.jpg", acteurs: "Margot Robbie, Mary Elizabeth Winstead", genres: ["Action", "Comédie"] },
    { titre: "black_adam", video: "https://www.youtube.com/watch?v=vUnRitCWjqc", image: "images/black_adam.jpg", acteurs: "Dwayne Johnson, Sarah Shahi", genres: ["Action", "Aventure"] },
    { titre: "black_k_klasman", video: "https://www.youtube.com/watch?v=zvTxYdsWbKk&t=29s", image: "images/black_k_klasman.jpg", acteurs: "John David Washington, Adam Driver", genres: ["Comédie"] },
    { titre: "black_panther", video: "https://www.youtube.com/watch?v=lyKngqfmqW4", image: "images/black_panther.jpg", acteurs: "Chadwick Boseman, Michael B. Jordan", genres: ["Action", "Science-fiction"] },
    { titre: "black_panther_wakanda_forever", video: "https://www.youtube.com/watch?v=Pa4BEJcrMAA", image: "images/black_panther_wakanda_forever.jpg", acteurs: "Letitia Wright, Lupita Nyong'o", genres: ["Action", "Science-fiction"] },
    { titre: "black_storm", video: "https://www.youtube.com/watch?v=hjqe0TjtsJs&t=33s", image: "images/black_storm.jpg", acteurs: "Richard Armitage, Sarah Wayne Callies", genres: ["Action", "Thriller"] },
    { titre: "black_widow", video: "https://www.youtube.com/watch?v=4l99M0zOEaA&t=35s", image: "images/black_widow.jpg", acteurs: "Scarlett Johansson, Florence Pugh", genres: ["Action", "Thriller"] },
    { titre: "blade_runner_2049", video: "https://www.youtube.com/watch?v=O4C5cwSbXZ8&t=29s", image: "images/blade_runner_2049.jpg", acteurs: "Ryan Gosling, Harrison Ford", genres: ["Science-fiction", "Thriller"] },
    { titre: "bodyguard", video: "https://www.youtube.com/watch?v=AhIJMuPHWVQ&t=27s", image: "images/bodyguard.jpg", acteurs: "Kevin Costner, Whitney Houston", genres: ["Romance", "Thriller"] },
    { titre: "bohemian_rhapsody", video: "https://www.youtube.com/watch?v=xXuDGUviTgA", image: "images/bohemian_rhapsody.jpg", acteurs: "Rami Malek, Lucy Boynton", genres: ["Musical"] },
    { titre: "ca_1", video: "https://www.youtube.com/watch?v=Tw3yT-qAbvc", image: "images/ca_1.jpg", acteurs: "Bill Skarsgård, Jaeden Martell", genres: ["Horreur"] },
    { titre: "ca_2", video: "https://www.youtube.com/watch?v=yOZA2y_dQA4", image: "images/ca_2.jpg", acteurs: "Bill Skarsgård, James McAvoy", genres: ["Horreur"] },
    { titre: "captain_america_1", video: "https://www.youtube.com/watch?v=IsiV9IJieMk&t=17s", image: "images/captain_america_1.jpg", acteurs: "Chris Evans, Hayley Atwell", genres: ["Action", "Aventure"] },
    { titre: "captain_america_civil_war", video: "https://www.youtube.com/watch?v=fuIIGDjEj8Q&t=47s", image: "images/captain_america_civil_war.jpg", acteurs: "Chris Evans, Robert Downey Jr.", genres: ["Action", "Aventure"] },
    { titre: "captain_america_le_soldat_d_hiver", video: "https://www.youtube.com/watch?v=Zp1L2kc9p1I", image: "images/captain_america_le_soldat_d_hiver.jpg", acteurs: "Chris Evans, Sebastian Stan", genres: ["Action", "Aventure"] },
    { titre: "captain_marvel", video: "https://www.youtube.com/watch?v=rndLWLmwgeA", image: "images/captain_marvel.jpg", acteurs: "Brie Larson, Samuel L. Jackson", genres: ["Action", "Aventure"] },
    { titre: "captivity", video: "https://www.youtube.com/watch?v=Ncmo6Tig2Vk", image: "images/captivity.jpg", acteurs: "Elisha Cuthbert, Daniel Gillies", genres: ["Science-fiction"] },
    { titre: "cocktail", video: "https://www.youtube.com/watch?v=N2_6tS80-Pw", image: "images/cocktail.jpg", acteurs: "Tom Cruise, Bryan Brown", genres: ["Romance", "Comédie"] },
    { titre: "contagion", video: "https://www.youtube.com/watch?v=MSgq3CgV7_A", image: "images/contagion.jpg", acteurs: "Matt Damon, Kate Winslet", genres: ["Science-fiction", "Thriller"] },
    { titre: "da_vinci_code", video: "https://www.youtube.com/watch?v=dOJBaIjXGnQ&t=39s", image: "images/da_vinci_code.jpg", acteurs: "Tom Hanks, Audrey Tautou", genres: ["Thriller", "Mystère"] },
    { titre: "deadpool_1", video: "https://www.youtube.com/watch?v=XWtH7anz7io&t=72s", image: "images/deadpool_1.jpg", acteurs: "Ryan Reynolds, Morena Baccarin", genres: ["Action", "Comédie"] },
    { titre: "deadpool_2", video: "https://www.youtube.com/watch?v=QgzslSsSECM", image: "images/deadpool_2.jpg", acteurs: "Ryan Reynolds, Josh Brolin", genres: ["Action", "Comédie"] },
    { titre: "destination_finale_1", video: "https://www.youtube.com/watch?v=Mog5aEuq-8A&t=2s", image: "images/destination_finale_1.jpg", acteurs: "Devon Sawa, Ali Larter", genres: ["Horreur"] },
    { titre: "destination_finale_2", video: "https://www.youtube.com/watch?v=NqK9Gbrnyec&t=8s", image: "images/destination_finale_2.jpg", acteurs: "A.J. Cook, Ali Larter", genres: ["Horreur"] },
    { titre: "destination_finale_3", video: "https://www.youtube.com/watch?v=iqVxVKL-yOM", image: "images/destination_finale_3.jpg", acteurs: "Mary Elizabeth Winstead, Ryan Merriman", genres: ["Horreur"] },
    { titre: "destination_finale_4", video: "https://www.youtube.com/watch?v=PBF4DTFUZKg&t=15s", image: "images/destination_finale_4.jpg", acteurs: "Bobby Campo, Shantel VanSanten", genres: ["Horreur"] },
    { titre: "destination_finale_5", video: "https://www.youtube.com/watch?v=VjqCOYHrd5s", image: "images/destination_finale_5.jpg", acteurs: "Nicholas D'Agosto, Emma Bell", genres: ["Horreur"] },
    { titre: "die_hard_4_retour_en_enfer", video: "https://www.youtube.com/watch?v=IQuquL2xuzY&t=36s", image: "images/die_har_4_retour_en_enfer.jpg", acteurs: "Bruce Willis, Justin Long", genres: ["Action", "Thriller"] },
    { titre: "die_hard_1", video: "https://www.youtube.com/watch?v=rf79c9Da83I&t=3s", image: "images/die_hard_1.jpg", acteurs: "Bruce Willis, Alan Rickman", genres: ["Action", "Thriller"] },
    { titre: "die_hard_2_58_min_pour_vivre", video: "https://www.youtube.com/watch?v=dC9UCRMxoZg&t=45s", image: "images/die_hard_2_58_min.jpg", acteurs: "Bruce Willis, William Atherton", genres: ["Action", "Thriller"] },
    { titre: "die_hard_3_une_journee_en_enfer", video: "https://www.youtube.com/watch?v=K2AruxS8-Rs", image: "images/die_hard_3_une_journee_en_enfer.jpg", acteurs: "Bruce Willis, Samuel L. Jackson", genres: ["Action", "Thriller"] },
    { titre: "die_hard_5_belle_journee_pour_mourir", video: "https://www.youtube.com/watch?v=IBX_A-5iWYA&t=41s", image: "images/die_hard_5_belle_journee_pour_mourir.jpg", acteurs: "Bruce Willis, Jai Courtney", genres: ["Action", "Thriller"] },
    { titre: "divergeante_1", video: "https://www.youtube.com/watch?v=gxbwcBlj_dM&t=63s", image: "images/divergeante_1.jpg", acteurs: "Shailene Woodley, Theo James", genres: ["Action", "Science-fiction"] },
    { titre: "divergeante_2", video: "https://www.youtube.com/watch?v=l4YTrX3gmco&t=28s", image: "images/divergeante_2.jpg", acteurs: "Shailene Woodley, Theo James", genres: ["Action", "Science-fiction"] },
    { titre: "divergeante_3", video: "https://www.youtube.com/watch?v=IME-Af-uRSE&t=29s", image: "images/divergeante_3.jpg", acteurs: "Shailene Woodley, Theo James", genres: ["Action", "Science-fiction"] },
    { titre: "doctor_strange", video: "https://www.youtube.com/watch?v=bly7XM7QzSY&t=43s", image: "images/doctor_strange.jpg", acteurs: "Benedict Cumberbatch, Chiwetel Ejiofor", genres: ["Action"] },
    { titre: "doctor_strange_in_the_multiverse_of_madness", video: "https://www.youtube.com/watch?v=IB0keJtKDvw", image: "images/doctor_strange_in_the_multiverse_of_madness.jpg", acteurs: "Benedict Cumberbatch, Elizabeth Olsen", genres: ["Action"] },
    { titre: "donjons_et_dragons", video: "https://www.youtube.com/watch?v=wK69QJ2ESO0", image: "images/donjons_et_dragons.jpeg", acteurs: "Chris Pine, Michelle Rodriguez", genres: ["Action"] },
    { titre: "dunkerque", video: "https://www.youtube.com/watch?v=chRUCIk3K94&t=66s", image: "images/dunkerque.jpg", acteurs: "Fionn Whitehead, Tom Hardy, Mark Rylance", genres: ["Guerre", "Action"] },
    { titre: "expandable_1", video: "https://www.youtube.com/watch?v=5RcnSc08lJQ&t=30s", image: "images/expandable_1.jpg", acteurs: "Sylvester Stallone, Jason Statham", genres: ["Action", "Thriller"] },
    { titre: "expandable_2", video: "https://www.youtube.com/watch?v=PTEBUh76o-Y", image: "images/expandable_2.jpg", acteurs: "Sylvester Stallone, Jason Statham, Jean-Claude Van Damme", genres: ["Action", "Thriller"] },
    { titre: "expandable_3", video: "https://www.youtube.com/watch?v=RwgHXmnUDBw&t=29s", image: "images/expandable_3.jpg", acteurs: "Sylvester Stallone, Jason Statham, Mel Gibson", genres: ["Action", "Thriller"] },
    { titre: "fast_and_furios_10", video: "https://www.youtube.com/watch?v=rPmA-4AhA94", image: "images/fast_and_furios_10.jpg", acteurs: "Vin Diesel, Michelle Rodriguez", genres: ["Action"] },
    { titre: "fast_and_furious_1", video: "https://www.youtube.com/watch?v=b0EJzs6U9t8&t=30s", image: "images/fast_and_furious_1.jpg", acteurs: "Vin Diesel, Paul Walker", genres: ["Action"] },
    { titre: "fast_and_furious_2", video: "https://www.youtube.com/watch?v=KUX6KI3-AjA&t=1s", image: "images/fast_and_furious_2.jpg", acteurs: "Paul Walker, Tyrese Gibson", genres: ["Action"] },
    { titre: "fast_and_furious_3", video: "https://www.youtube.com/watch?v=KPiJgEc7Ux8&t=4s", image: "images/fast_and_furious_3.jpg", acteurs: "Lucas Black, Sung Kang", genres: ["Action"] },
    { titre: "fast_and_furious_4", video: "https://www.youtube.com/watch?v=99XOxDLMvBg&t=4s", image: "images/fast_and_furious_4.jpg", acteurs: "Vin Diesel, Paul Walker", genres: ["Action"] },
    { titre: "fast_and_furious_5", video: "https://www.youtube.com/watch?v=CYV-mTqlI_g&t=6s", image: "images/fast_and_furious_5.jpg", acteurs: "Vin Diesel, Paul Walker, Dwayne Johnson", genres: ["Action"] },
    { titre: "fast_and_furious_6", video: "https://www.youtube.com/watch?v=Ewu0WTPbOVY&t=1s", image: "images/fast_and_furious_6.jpg", acteurs: "Vin Diesel, Paul Walker, Dwayne Johnson", genres: ["Action"] },
    { titre: "fast_and_furious_7", video: "https://www.youtube.com/watch?v=3Wu2BhFuc4c", image: "images/fast_and_furious_7.jpg", acteurs: "Vin Diesel, Paul Walker, Jason Statham", genres: ["Action"] },
    { titre: "fast_and_furious_8", video: "https://www.youtube.com/watch?v=xFO-pKB13mw", image: "images/fast_and_furious_8.jpg", acteurs: "Vin Diesel, Dwayne Johnson, Charlize Theron", genres: ["Action"] },
    { titre: "fast_and_furious_9", video: "https://www.youtube.com/watch?v=Eumj0-UxrQM", image: "images/fast_and_furious_9.jpg", acteurs: "Vin Diesel, John Cena", genres: ["Action"] },
    { titre: "fast_and_furious_hobbs", video: "https://www.youtube.com/watch?v=VZFp6OIeX2Q", image: "images/fast_and_furious_hobbs.jpg", acteurs: "Dwayne Johnson, Jason Statham", genres: ["Action"] },
    { titre: "forrest_gump", video: "https://www.youtube.com/watch?v=7pDDuroFBGM", image: "images/forrest_gump.jpg", acteurs: "Tom Hanks, Robin Wright", genres: ["Comédie"] },
    { titre: "freddy_1", video: "https://www.youtube.com/watch?v=OuqHdlQ7DBM&t=52s", image: "images/freddy_1.jpg", acteurs: "Robert Englund, Heather Langenkamp", genres: ["Horreur"] },
    { titre: "freddy_2", video: "https://www.youtube.com/watch?v=SUF13QSUUQA", image: "images/freddy_2.jpg", acteurs: "Robert Englund, Mark Patton", genres: ["Horreur"] },
    { titre: "freddy_3", video: "https://www.youtube.com/watch?v=c1Zgra_gHMU&t=21s", image: "images/freddy_3.jpg", acteurs: "Robert Englund, Heather Langenkamp", genres: ["Horreur"] },
    { titre: "freddy_4", video: "https://www.youtube.com/watch?v=wmDM090Z2SI", image: "images/freddy_4.jpg", acteurs: "Robert Englund, Rodney Eastman", genres: ["Horreur"] },
    { titre: "game_of_thrones", video: "https://www.youtube.com/watch?v=Ng1W_qu5aJM", image: "images/game_of_thrones.jpg", acteurs: "Kit Harington, Emilia Clarke", genres: ["Serie"] },
    { titre: "gemini_man", video: "https://www.youtube.com/watch?v=AK07MzdsrD4&t=60s", image: "images/gemini_man.jpg", acteurs: "Will Smith, Mary Elizabeth Winstead", genres: ["Action", "Thriller"] },
    { titre: "geostorm", video: "https://www.youtube.com/watch?v=QWaOHVtjUoc", image: "images/geostorm.jpg", acteurs: "Gerard Butler, Jim Sturgess", genres: ["Action", "Science-fiction"] },
    { titre: "ghost", video: "https://www.youtube.com/watch?v=zUY8bf4mUPg&t=28s", image: "images/ghost.jpg", acteurs: "Patrick Swayze, Demi Moore", genres: ["Romance", "Thriller"] },
    { titre: "grease", video: "https://www.youtube.com/watch?v=2j17nSmVghI", image: "images/grease.jpg", acteurs: "John Travolta, Olivia Newton-John", genres: ["Musical", "Comédie"] },
    { titre: "hancock", video: "https://www.youtube.com/watch?v=FmpOgGrwXdQ&t=29s", image: "images/hancock.jpg", acteurs: "Will Smith, Charlize Theron", genres: [] },
    { titre: "harry_potter_1", video: "https://www.youtube.com/watch?v=P1BGgqhVGAI", image: "images/harry_potter_1.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_2", video: "https://www.youtube.com/watch?v=Z3T8PuWuoL0&t=47s", image: "images/harry_potter_2.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_3", video: "https://www.youtube.com/watch?v=CLncEeVf4ks&t=7s", image: "images/harry_potter_3.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_4", video: "https://www.youtube.com/watch?v=XO9rqIgzDL0&t=3s", image: "images/harry_potter_4.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_5", video: "https://www.youtube.com/watch?v=S8-SXEGMmi4&t=1s", image: "images/harry_potter_5.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_6", video: "https://www.youtube.com/watch?v=yb-VYG3x5E8", image: "images/harry_potter_6.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_7", video: "https://www.youtube.com/watch?v=HgZZsnleZJQ&t=1s", image: "images/harry_potter_7.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "harry_potter_8", video: "https://www.youtube.com/watch?v=aiaIfICU-Tk&t=3s", image: "images/harry_potter_8.jpg", acteurs: "Daniel Radcliffe, Emma Watson, Rupert Grint", genres: [] },
    { titre: "hunger_games_1", video: "https://www.youtube.com/watch?v=wqUq0lsQ684&t=19s", image: "images/hunger_games_1.jpg", acteurs: "Jennifer Lawrence, Josh Hutcherson", genres: [] },
    { titre: "hunger_games_2", video: "https://www.youtube.com/watch?v=-ZcW_6i2Rkg", image: "images/hunger_games_2.jpg", acteurs: "Jennifer Lawrence, Josh Hutcherson", genres: [] },
    { titre: "hunger_games_3", video: "https://www.youtube.com/watch?v=zdMIft77FEY&t=41s", image: "images/hunger_games_3.jpg", acteurs: "Jennifer Lawrence, Josh Hutcherson", genres: [] },
    { titre: "hunger_games_4", video: "https://www.youtube.com/watch?v=MGZ0kzmcWAU&t=22s", image: "images/hunger_games_4.jpg", acteurs: "Jennifer Lawrence, Josh Hutcherson", genres: [] },
    { titre: "il_faut_sauver_le_soldat", video: "https://www.youtube.com/watch?v=7VBsDfsXJfQ", image: "images/il_faut_sauver_le_soldat.jpg", acteurs: "Tom Hanks, Matt Damon", genres: [] },
    { titre: "inception", video: "https://www.youtube.com/watch?v=HcoZbHBDHQA", image: "images/inception.jpg", acteurs: "Leonardo DiCaprio, Joseph Gordon-Levitt", genres: [] },
    { titre: "independance_day_1", video: "https://www.youtube.com/watch?v=B1E7h3SeMDk&t=31s", image: "images/independance_day_1.jpg", acteurs: "Will Smith, Bill Pullman", genres: [] },
    { titre: "independance_day_2", video: "https://www.youtube.com/watch?v=b577i7s2CiM", image: "images/independance_day_2.jpg", acteurs: "Liam Hemsworth, Jeff Goldblum", genres: [] },
    { titre: "inferno", video: "https://www.youtube.com/watch?v=GfXpBiLwhHk&t=16s", image: "images/inferno.jpg", acteurs: "Tom Hanks, Felicity Jones", genres: [] },
    { titre: "insaisissables_1", video: "https://www.youtube.com/watch?v=-FeFz-cXILA", image: "images/insaisissables_1.jpg", acteurs: "Jesse Eisenberg, Mark Ruffalo", genres: [] },
    { titre: "insaisissables_2", video: "https://www.youtube.com/watch?v=0iGn57DVJIc", image: "images/insaisissables_2.jpg", acteurs: "Jesse Eisenberg, Mark Ruffalo, Daniel Radcliffe", genres: [] },
    { titre: "intouchable", video: "https://www.youtube.com/watch?v=EsaX5kltRcA&t=33s", image: "images/intouchable.jpg", acteurs: "François Cluzet, Omar Sy", genres: [] },
    { titre: "iron_man_1", video: "https://www.youtube.com/watch?v=rDCTb9Gp2qk&t=34s", image: "images/iron_man_1.jpg", acteurs: "Robert Downey Jr., Gwyneth Paltrow", genres: [] },
    { titre: "iron_man_2", video: "https://www.youtube.com/watch?v=0Y7ullsUPEA", image: "images/iron_man_2.jpg", acteurs: "Robert Downey Jr., Gwyneth Paltrow", genres: [] },
    { titre: "iron_man_3", video: "https://www.youtube.com/watch?v=wnEr73Rq3Ac&t=51s", image: "images/iron_man_3.jpg", acteurs: "Robert Downey Jr., Gwyneth Paltrow", genres: [] },
    { titre: "jean_philippe", video: "https://www.youtube.com/watch?v=RnN3tT1Utxs&t=34s", image: "images/jean_philippe.jpg", acteurs: "Fabrice Luchini, Johnny Hallyday", genres: [] },
    { titre: "john_wick_1", video: "https://www.youtube.com/watch?v=pWK5crMuhHY&t=37s", image: "images/john_wick_1.jpg", acteurs: "Keanu Reeves, Michael Nyqvist", genres: [] },
    { titre: "john_wick_2", video: "https://www.youtube.com/watch?v=d0u1o8vdxE8&t=27s", image: "images/john_wick_2.jpg", acteurs: "Keanu Reeves, Riccardo Scamarcio", genres: [] },
    { titre: "john_wick_3", video: "https://www.youtube.com/watch?v=Cs4wKxXjkc8&t=28s", image: "images/john_wick_3.jpg", acteurs: "Keanu Reeves, Halle Berry", genres: [] },
    { titre: "john_wick_4", video: "https://www.youtube.com/watch?v=6itn_8L6-Z8&t=27s", image: "images/john_wick_4.jpg", acteurs: "Keanu Reeves", genres: [] },
    { titre: "joker", video: "https://www.youtube.com/watch?v=OoTx1cYC5u8", image: "images/joker.jpg", acteurs: "Joaquin Phoenix, Robert De Niro", genres: [] },
    { titre: "joyeux_bordel", video: "https://www.youtube.com/watch?v=ifk8lQ_5b6Y", image: "images/joyeux_bordel.jpg", acteurs: "Jason Bateman, Olivia Munn", genres: [] },
    { titre: "jumanji", video: "https://www.youtube.com/watch?v=oZI2njF5rx0", image: "images/jumanji.jpg", acteurs: "Dwayne Johnson, Kevin Hart, Jack Black", genres: [] },
    { titre: "jumanji_2", video: "https://www.youtube.com/watch?v=RhWRa0wBBHA", image: "images/jumanji_2.jpg", acteurs: "Dwayne Johnson, Kevin Hart, Jack Black", genres: [] },
    { titre: "jungle_cruise", video: "https://www.youtube.com/watch?v=CWpcUeAZgD0&t=43s", image: "images/jungle_cruise.jpg", acteurs: "Dwayne Johnson, Emily Blunt", genres: [] },
    { titre: "jurassic_park_1", video: "https://www.youtube.com/watch?v=ZEY7iMX_oZs&t=41s", image: "images/jurassic_park_1.jpg", acteurs: "Sam Neill, Laura Dern, Jeff Goldblum", genres: [] },
    { titre: "jurassic_park_2", video: "https://www.youtube.com/watch?v=z6hwDlf8vMk&t=41s", image: "images/jurassic_park_2.jpg", acteurs: "Jeff Goldblum, Julianne Moore", genres: [] },
    { titre: "jurassic_park_3", video: "https://www.youtube.com/watch?v=FxOfakcWAeE", image: "images/jurassic_park_3.jpg", acteurs: "Sam Neill, William H. Macy", genres: [] },
    { titre: "jurassic_park_4", video: "https://www.youtube.com/watch?v=wmzAfqhphq8", image: "images/jurassic_park_4.jpg", acteurs: "Chris Pratt, Bryce Dallas Howard", genres: [] },
    { titre: "jurassic_park_5", video: "https://www.youtube.com/watch?v=6Eokj_7aIQ0", image: "images/jurassic_park_5.jpg", acteurs: "Chris Pratt, Bryce Dallas Howard", genres: [] },
    { titre: "justice_league", video: "https://www.youtube.com/watch?v=cvUFoxU_Lq0&t=28s", image: "images/justice_league.jpg", acteurs: "Ben Affleck, Gal Gadot, Henry Cavill", genres: [] },
    { titre: "justice_league_zack_snider", video: "https://www.youtube.com/watch?v=nKmVTdkUI6A", image: "images/justice_league_zack_snider.jpg", acteurs: "Ben Affleck, Gal Gadot, Henry Cavill", genres: [] },
    { titre: "kin", video: "https://www.youtube.com/watch?v=KGsqiAF6MJk&t=49s", image: "images/kin.jpg", acteurs: "Myles Truitt, Jack Reynor", genres: [] },
    { titre: "kings_man_1", video: "https://www.youtube.com/watch?v=s-YfBT7Wu9o", image: "images/kings_man_1.jpg", acteurs: "Taron Egerton, Colin Firth", genres: [] },
    { titre: "kings_man_2", video: "https://www.youtube.com/watch?v=QImgyRave8c", image: "images/kings_man_2.jpg", acteurs: "Taron Egerton, Colin Firth, Julianne Moore", genres: [] },
    { titre: "kings_man_3", video: "https://www.youtube.com/watch?v=QMQ53iuCsp0", image: "images/kings_man_3.jpg", acteurs: "Ralph Fiennes, Harris Dickinson", genres: [] },
    { titre: "kite", video: "https://www.youtube.com/watch?v=B7_hddE3i4k&t=3s", image: "images/kite.jpg", acteurs: "India Eisley, Callan McAuliffe", genres: [] },
    { titre: "knock_knock", video: "https://www.youtube.com/watch?v=RxFWCjH_t6k&t=31s", image: "images/knock_knock.jpg", acteurs: "Keanu Reeves, Lorenza Izzo", genres: [] },
    { titre: "la_boum_1", video: "https://www.youtube.com/watch?v=uqKKiUSLZK8", image: "images/la_boum_1.jpg", acteurs: "Sophie Marceau, Claude Brasseur", genres: [] },
    { titre: "la_boum_2", video: "https://www.youtube.com/watch?v=NnHZuv7ITic&t=41s", image: "images/la_boum_2.jpg", acteurs: "Sophie Marceau, Claude Brasseur", genres: [] },
    { titre: "la_famille_belier", video: "https://www.youtube.com/watch?v=tEgw97vpkDM&t=26s", image: "images/la_famille_belier.jpg", acteurs: "Louane Emera, Karin Viard", genres: [] },
    { titre: "la_ligne_verte", video: "https://www.youtube.com/watch?v=mccs8Ql8m8o&t=32s", image: "images/la_ligne_verte.jpg", acteurs: "Tom Hanks, Michael Clarke Duncan", genres: [] },
    { titre: "la_mule", video: "https://www.youtube.com/watch?v=bGgyUSO24BA", image: "images/la_mule.jpg", acteurs: "Clint Eastwood, Bradley Cooper", genres: [] },
    { titre: "la_petite_sirene", video: "https://www.youtube.com/watch?v=J5VvzJmiqJc", image: "images/la_petite_sirene.jpg", acteurs: "Jodi Benson, Christopher Daniel Barnes (voices)", genres: [] },
    { titre: "la_planete_des_singes_1", video: "https://www.youtube.com/watch?v=Vn8GriIog1s&t=25s", image: "images/la_planete_des_singes_1.jpg", acteurs: "Mark Wahlberg, Tim Roth", genres: [] },
    { titre: "la_planete_des_singes_2", video: "https://www.youtube.com/watch?v=dPcwB7okdzU&t=30s", image: "images/la_planete_des_singes_2.jpg", acteurs: "Andy Serkis, Jason Clarke", genres: [] },
    { titre: "la_planete_des_singes_3", video: "https://www.youtube.com/watch?v=GyUI-Cr9lak&t=53s", image: "images/la_planete_des_singes_3.jpg", acteurs: "Andy Serkis, Woody Harrelson", genres: [] },
    { titre: "largo_winch", video: "https://www.youtube.com/watch?v=rnYZHu_YaQY&t=28s", image: "images/largo_winch.jpg", acteurs: "Tomer Sisley, Kristin Scott Thomas", genres: [] },
    { titre: "l_arme_fatale_1", video: "https://www.youtube.com/watch?v=OeBVtCT6HW8", image: "images/larme_fatale_1.jpg", acteurs: "Mel Gibson, Danny Glover", genres: [] },
    { titre: "l_arme_fatale_2", video: "https://www.youtube.com/watch?v=5AdW-ShY9T4", image: "images/larme_fatale_2.jpg", acteurs: "Mel Gibson, Danny Glover", genres: [] },
    { titre: "l_arme_fatale_3", video: "https://www.youtube.com/watch?v=w0Y6L5Y9M3s&t=32s", image: "images/larme_fatale_3.jpg", acteurs: "Mel Gibson, Danny Glover", genres: [] },
    { titre: "l_arme_fatale_4", video: "https://www.youtube.com/watch?v=Es4CYLavwuw&t=37s", image: "images/larme_fatale_4.jpg", acteurs: "Mel Gibson, Danny Glover", genres: [] },
    { titre: "le_crime_de_l'orient_express", video: "https://www.youtube.com/watch?v=FMlYxRCBSSM", image: "images/le_crime.jpg", acteurs: "Kenneth Branagh, Johnny Depp", genres: [] },
    { titre: "le_doudou", video: "https://www.youtube.com/watch?v=P4_rE7qGXFE&t=30s", image: "images/le_doudou.jpg", acteurs: "Kad Merad, Malik Bentalha", genres: [] },
    { titre: "le_drole_de_noel_de_scroodge", video: "https://www.youtube.com/watch?v=PcNLFXSdO5A&t=47s", image: "images/le_drole_de_noel_de_scroodge.jpg", acteurs: "Jim Carrey, Gary Oldman (voices)", genres: [] },
    { titre: "le_grand_bleu", video: "https://www.youtube.com/watch?v=xGmVAPwWwSM", image: "images/le_grand_bleu.jpg", acteurs: "Jean-Marc Barr, Jean Reno", genres: [] },
    { titre: "le_hobbit_1", video: "https://www.youtube.com/watch?v=tiy7peMH3g8&t=35s", image: "images/le_hobbit_1.jpg", acteurs: "Martin Freeman, Ian McKellen", genres: [] },
    { titre: "le_hobbit_2", video: "https://www.youtube.com/watch?v=bvKLagxYhrc&t=28s", image: "images/le_hobbit_2.jpg", acteurs: "Martin Freeman, Benedict Cumberbatch", genres: [] },
    { titre: "le_hobbit_3", video: "https://www.youtube.com/watch?v=E5qN3zUF3Rw", image: "images/le_hobbit_3.jpg", acteurs: "Martin Freeman, Ian McKellen", genres: [] },
    { titre: "le_jeu", video: "https://www.youtube.com/watch?v=1fGdZehIGFE", image: "images/le_jeu.jpg", acteurs: "Bérénice Bejo, Suzanne Clément", genres: [] },
    { titre: "le_labirynthe", video: "https://www.youtube.com/watch?v=LyPiCH_4Al4", image: "images/le_labirynthe.jpg", acteurs: "Dylan O'Brien, Kaya Scodelario", genres: [] },
    { titre: "le_labirynthe_2", video: "https://www.youtube.com/watch?v=K7jyL2cS6dc", image: "images/le_labirynthe_2.jpg", acteurs: "Dylan O'Brien, Kaya Scodelario", genres: [] },
    { titre: "le_labirynthe_3", video: "https://www.youtube.com/watch?v=HuXEKU0PTzw", image: "images/le_labirynthe_3.jpg", acteurs: "Dylan O'Brien, Kaya Scodelario", genres: [] },
    { titre: "le_mans_66", video: "https://www.youtube.com/watch?v=UG3Z-MIDdGs", image: "images/le_mans_66.jpg", acteurs: "Matt Damon, Christian Bale", genres: [] },
    { titre: "le_monde_fantastique_d_oz", video: "https://www.youtube.com/watch?v=2Hsq8qq0jdo&t=45s", image: "images/le_monde_fantastique_doz.jpg", acteurs: "James Franco, Mila Kunis", genres: [] },
    { titre: "le_prestige", video: "https://www.youtube.com/watch?v=2zVbrV1ehnU", image: "images/le_prestige.jpg", acteurs: "Christian Bale, Hugh Jackman", genres: [] },
    { titre: "le_seigneur_des_anneaux_1", video: "https://www.youtube.com/watch?v=nalLU8i4zgs", image: "images/le_seigneur_des_anneaux_1.jpg", acteurs: "Elijah Wood, Ian McKellen", genres: [] },
    { titre: "le_seigneur_des_anneaux_2", video: "https://www.youtube.com/watch?v=c9blKqmyeV4", image: "images/le_seigneur_des_anneaux_2.jpg", acteurs: "Elijah Wood, Ian McKellen", genres: [] },
    { titre: "le_seigneur_des_anneaux_3", video: "https://www.youtube.com/watch?v=RCuDRcK0BBM", image: "images/le_seigneur_des_anneaux_3.jpg", acteurs: "Elijah Wood, Ian McKellen", genres: [] },
    { titre: "le_transporteur_heritage", video: "https://www.youtube.com/watch?v=DRuyPTWsydY&t=30s", image: "images/le_transporteur_heritage.jpg", acteurs: "Ed Skrein, Ray Stevenson", genres: [] },
    { titre: "leon", video: "https://www.youtube.com/watch?v=M242Bp0PcwE", image: "images/leon.jpg", acteurs: "Jean Reno, Natalie Portman", genres: [] },
    { titre: "les_animaux_fantastiques", video: "https://www.youtube.com/watch?v=jC8xuFcMq20", image: "images/les_animaux_fantastiques.jpg", acteurs: "Eddie Redmayne, Katherine Waterston", genres: [] },
    { titre: "les_animaux_fantastiques_2", video: "https://www.youtube.com/watch?v=Dnb6eAfSHtw&t=47s", image: "images/les_animaux_fantastiques_2.jpg", acteurs: "Eddie Redmayne, Johnny Depp", genres: [] },
    { titre: "les_animaux_fantastiques_3", video: "https://www.youtube.com/watch?v=k39acJCDSKY", image: "images/les_animaux_fantastiques_3.jpg", acteurs: "Eddie Redmayne, Jude Law", genres: [] },
    { titre: "les_chevaliers_du_zodiac", video: "https://www.youtube.com/watch?v=nEWL1GQ5Pks", image: "images/les_chevaliers_du_zodiac.jpg", acteurs: "", genres: [] },
    { titre: "les_eternels", video: "https://www.youtube.com/watch?v=nHcubNwuKFA&t=31s", image: "images/les_eternelles.jpg", acteurs: "Gemma Chan, Richard Madden", genres: [] },
    { titre: "les_gardiens_de_la_galaxie_1", video: "https://www.youtube.com/watch?v=HbB1LC_QyK0&t=24s", image: "images/les_gardiens_de_la_galaxie_1.jpg", acteurs: "Chris Pratt, Zoe Saldana", genres: [] },
    { titre: "les_gardiens_de_la_galaxie_2", video: "https://www.youtube.com/watch?v=e2LkglavLRs&t=37s", image: "images/les_gardiens_de_la_galaxie_2.jpg", acteurs: "Chris Pratt, Zoe Saldana", genres: [] },
    { titre: "les_gardiens_de_la_galaxie_3", video: "https://www.youtube.com/watch?v=0RsvBSFm938", image: "images/les_gardiens_de_la_galaxie_3.jpg", acteurs: "Chris Pratt, Zoe Saldana", genres: [] },
    { titre: "les_schtroumpfs", video: "https://www.youtube.com/watch?v=3GclcezQvFU&t=31s", image: "images/les_schtroumphs.jpg", acteurs: "Neil Patrick Harris, Jayma Mays (live-action)", genres: [] },
    { titre: "les_tuche_1", video: "https://www.youtube.com/watch?v=ndCzT6dyOqk&t=36s", image: "images/les_tuche_1.jpg", acteurs: "Jean-Paul Rouve, Isabelle Nanty", genres: [] },
    { titre: "les_tuche_2", video: "https://www.youtube.com/watch?v=pKbox8S-se4&t=31s", image: "images/les_tuche_2.jpg", acteurs: "Jean-Paul Rouve, Isabelle Nanty", genres: [] },
    { titre: "les_tuche_3", video: "https://www.youtube.com/watch?v=WqSPFOLA9sE&t=26s", image: "images/les_tuche_3.jpg", acteurs: "Jean-Paul Rouve, Isabelle Nanty", genres: [] },
    { titre: "les_tuche_4", video: "https://www.youtube.com/watch?v=vxWSTApFmR4", image: "images/les_tuche_4.jpg", acteurs: "Jean-Paul Rouve, Isabelle Nanty", genres: [] },
    { titre: "l_incroyable_hulk", video: "https://www.youtube.com/watch?v=LCjTxK1B5Pg&t=38s", image: "images/lincroyable_hulk.jpg", acteurs: "Edward Norton, Liv Tyler", genres: [] },
    { titre: "logan", video: "https://www.youtube.com/watch?v=i-iqiI5uikE", image: "images/logan.jpg", acteurs: "Hugh Jackman, Patrick Stewart", genres: [] },
    { titre: "malefique_1", video: "https://www.youtube.com/watch?v=8yBDfD88W3U&t=48s", image: "images/malefique_1.jpg", acteurs: "Angelina Jolie, Elle Fanning", genres: [] },
    { titre: "malefique_2", video: "https://www.youtube.com/watch?v=R2kmlH2VkME&t=28s", image: "images/malefique_2.jpg", acteurs: "Angelina Jolie, Elle Fanning", genres: [] },
    { titre: "man_of_steel", video: "https://www.youtube.com/watch?v=Xw4VeR7tCxU&t=35s", image: "images/man_of_steel.jpg", acteurs: "Henry Cavill, Amy Adams", genres: [] },
    { titre: "matrix_1", video: "https://www.youtube.com/watch?v=8xx91zoASLY&t=27s", image: "images/matrix_1.jpg", acteurs: "Keanu Reeves, Laurence Fishburne", genres: [] },
    { titre: "matrix_2", video: "https://www.youtube.com/watch?v=0ha2XYVC7_s&t=26s", image: "images/matrix_2.jpg", acteurs: "Keanu Reeves, Laurence Fishburne", genres: [] },
    { titre: "matrix_3", video: "https://www.youtube.com/watch?v=sK51m1tj_bE&t=31s", image: "images/matrix_3.jpg", acteurs: "Keanu Reeves, Laurence Fishburne", genres: [] },
    { titre: "matrix_4", video: "https://www.youtube.com/watch?v=Tj63xbpKnqo&t=26s", image: "images/matrix_4.jpg", acteurs: "Keanu Reeves, Carrie-Anne Moss", genres: [] },
    { titre: "top_gun_2_maverick", video: "https://www.youtube.com/watch?v=JYaFU81-t6c", image: "images/maverick.jpg", acteurs: "Tom Cruise, Miles Teller", genres: [] },
    { titre: "men_in_black_1", video: "https://www.youtube.com/watch?v=2wVy3QmCyJU&t=40s", image: "images/men_in_black_1.jpg", acteurs: "Will Smith, Tommy Lee Jones", genres: [] },
    { titre: "men_in_black_2", video: "https://www.youtube.com/watch?v=HuQmpzpAhHo&t=34s", image: "images/men_in_black_2.jpg", acteurs: "Will Smith, Tommy Lee Jones", genres: [] },
    { titre: "men_in_black_3", video: "https://www.youtube.com/watch?v=Ep6NGpX66oU&t=38s", image: "images/men_in_black_3.jpg", acteurs: "Will Smith, Josh Brolin", genres: [] },
    { titre: "men_in_black_international", video: "https://www.youtube.com/watch?v=JHQq7eOOxdc&t=39s", image: "images/men_in_black_international.jpg", acteurs: "Chris Hemsworth, Tessa Thompson", genres: [] },
    { titre: "midnight_express", video: "https://www.youtube.com/watch?v=OFVsGmNGGys&t=7s", image: "images/midnight_express.jpg", acteurs: "Brad Davis, John Hurt", genres: [] },
    { titre: "minority_report", video: "https://www.youtube.com/watch?v=V0Ay_CB9quU", image: "images/minority_report.jpg", acteurs: "Tom Cruise, Colin Farrell", genres: [] },
    { titre: "mission_impossible_1", video: "https://www.youtube.com/watch?v=EvOqiaqfewU&t=53s", image: "images/mission_impossible_1.jpg", acteurs: "Tom Cruise, Jon Voight", genres: [] },
    { titre: "mission_impossible_2", video: "https://www.youtube.com/watch?v=aHjhMW1WvWk&t=29s", image: "images/mission_impossible_2.jpg", acteurs: "Tom Cruise, Dougray Scott", genres: [] },
    { titre: "mission_impossible_3", video: "https://www.youtube.com/watch?v=Lb8mK7w_ig4&t=2s", image: "images/mission_impossible_3.jpg", acteurs: "Tom Cruise, Philip Seymour Hoffman", genres: [] },
    { titre: "mission_impossible_4", video: "https://www.youtube.com/watch?v=r5Pw_ntvbEo&t=5s", image: "images/mission_impossible_4.jpg", acteurs: "Tom Cruise, Jeremy Renner", genres: [] },
    { titre: "mission_impossible_5", video: "https://www.youtube.com/watch?v=wX8fhP-fsPg&t=20s", image: "images/mission_impossible_5.jpg", acteurs: "Tom Cruise, Rebecca Ferguson", genres: [] },
    { titre: "mission_impossible_6", video: "https://www.youtube.com/watch?v=n4qbj1lFEpU&t=4s", image: "images/mission_impossible_6.jpg", acteurs: "Tom Cruise, Henry Cavill", genres: [] },
    { titre: "moonfall", video: "https://www.youtube.com/watch?v=z3LNxIZI1go&t=32s", image: "images/moonfall.jpg", acteurs: "Halle Berry, Patrick Wilson", genres: [] },
    { titre: "morbius", video: "https://www.youtube.com/watch?v=6pGgkOcIyQA", image: "images/morbius.jpg", acteurs: "Jared Leto, Matt Smith", genres: [] },
    { titre: "nos_etoiles_contraires", video: "https://www.youtube.com/watch?v=X6WVLSdigCk&t=6s", image: "images/nos_eoiles_contraires.jpg", acteurs: "Shailene Woodley, Ansel Elgort", genres: [] },
    { titre: "nuit_blanche_a_seattle", video: "https://www.youtube.com/watch?v=XACtsPeHvxA", image: "images/nuit_blanche_a_seattle.jpg", acteurs: "Tom Hanks, Meg Ryan", genres: [] },
    { titre: "oblivion", video: "https://www.youtube.com/watch?v=XH1su3FVEA4&t=30s", image: "images/oblivion.jpg", acteurs: "Tom Cruise, Morgan Freeman", genres: [] },
    { titre: "pattaya", video: "https://www.youtube.com/watch?v=cICeyHsS16Y", image: "images/pattaya.jpg", acteurs: "Franck Gastambide, Malik Bentalha", genres: [] },
    { titre: "peppermint", video: "https://www.youtube.com/watch?v=EE1wg5HHwK0&t=1s", image: "images/peppermint.jpg", acteurs: "Jennifer Garner, John Gallagher Jr.", genres: [] },
    { titre: "peter_et_elliot_le_dragon", video: "https://www.youtube.com/watch?v=MEXN66uRNe8&t=33s", image: "images/peter_et_elliot_le_dragon.jpg", acteurs: "Oakes Fegley, Bryce Dallas Howard", genres: [] },
    { titre: "philadelphia", video: "https://www.youtube.com/watch?v=rYfl8rmZBKc&t=9s", image: "images/philadelphia.jpg", acteurs: "Tom Hanks, Denzel Washington", genres: [] },
    { titre: "pirate_des_caraibes_1", video: "https://www.youtube.com/watch?v=WiZC7l0ovvk", image: "images/pirate_des_caraibes_1.jpg", acteurs: "Johnny Depp, Orlando Bloom", genres: [] },
    { titre: "pirate_des_caraibes_2", video: "https://www.youtube.com/watch?v=ZJwdTWd8o_w", image: "images/pirate_des_caraibes_2.jpg", acteurs: "Johnny Depp, Orlando Bloom", genres: [] },
    { titre: "pirate_des_caraibes_3", video: "https://www.youtube.com/watch?v=rF6k1bXAVIg", image: "images/pirate_des_caraibes_3.jpg", acteurs: "Johnny Depp, Orlando Bloom", genres: [] },
    { titre: "pirate_des_caraibes_4", video: "https://www.youtube.com/watch?v=Kcqf4RqBaUI", image: "images/pirate_des_caraibes_4.jpg", acteurs: "Johnny Depp, Penélope Cruz", genres: [] },
    { titre: "pirate_des_caraibes_5", video: "https://www.youtube.com/watch?v=OTEGxxMTnPU", image: "images/pirate_des_caraibes_5.jpg", acteurs: "Johnny Depp, Javier Bardem", genres: [] },
    { titre: "point_break", video: "https://www.youtube.com/watch?v=5L7zkTFUxjo&t=35s", image: "images/point_break.jpg", acteurs: "Patrick Swayze, Keanu Reeves", genres: [] },
    { titre: "poseidon", video: "https://www.youtube.com/watch?v=TtZGfLoe1lA&t=31s", image: "images/poseidon.jpg", acteurs: "Josh Lucas, Kurt Russell", genres: [] },
    { titre: "pretty_woman", video: "https://www.youtube.com/watch?v=eBl8jzO6KHg", image: "images/pretty_woman.jpg", acteurs: "Richard Gere, Julia Roberts", genres: [] },
    { titre: "radin", video: "https://www.youtube.com/watch?v=8hmQFU2hpJM&t=34s", image: "images/radin.jpg", acteurs: "Dany Boon, Laurence Arné", genres: [] },
    { titre: "rain_man", video: "https://www.youtube.com/watch?v=G2q2IVHu8p4&t=39s", image: "images/rain_man.jpg", acteurs: "Dustin Hoffman, Tom Cruise", genres: [] },
    { titre: "rampage", video: "https://www.youtube.com/watch?v=8ckz-mk9-Tg", image: "images/rampage.jpg", acteurs: "Dwayne Johnson, Naomie Harris", genres: [] },
    { titre: "ready_player_one", video: "https://www.youtube.com/watch?v=oYGkAMHCOC4&t=42s", image: "images/ready_player.jpg", acteurs: "Tye Sheridan, Olivia Cooke", genres: [] },
    { titre: "remember_me", video: "https://www.youtube.com/watch?v=xi5I1JX0UIY&t=32s", image: "images/remember_me.jpg", acteurs: "Robert Pattinson, Emilie de Ravin", genres: [] },
    { titre: "replicas", video: "https://www.youtube.com/watch?v=CQopGH4qMEI&t=7s", image: "images/replicas.jpg", acteurs: "Keanu Reeves, Alice Eve", genres: [] },
    { titre: "resident_evil_1", video: "https://www.youtube.com/watch?v=amWEDXmkoXo", image: "images/resident_evil_1.jpg", acteurs: "Milla Jovovich, Michelle Rodriguez", genres: [] },
    { titre: "resident_evil_2", video: "https://www.youtube.com/watch?v=axd-h6a0Wgg", image: "images/resident_evil_2.jpg", acteurs: "Milla Jovovich, Sienna Guillory", genres: [] },
    { titre: "resident_evil_3", video: "https://www.youtube.com/watch?v=lb52BesCCa8", image: "images/resident_evil_3.jpg", acteurs: "Milla Jovovich, Oded Fehr", genres: [] },
    { titre: "resident_evil_4", video: "https://www.youtube.com/watch?v=eaKOg7w8meQ", image: "images/resident_evil_4.jpg", acteurs: "Milla Jovovich, Ali Larter", genres: [] },
    { titre: "resident_evil_5", video: "https://www.youtube.com/watch?v=65g5-p3CQcM", image: "images/resident_evil_5.jpg", acteurs: "Milla Jovovich, Sienna Guillory", genres: [] },
    { titre: "resident_evil_6", video: "https://www.youtube.com/watch?v=xHohwszlCEw", image: "images/resident_evil_6.png", acteurs: "Milla Jovovich, Iain Glen", genres: [] },
    { titre: "retour_vers_le_futur", video: "https://www.youtube.com/watch?v=cU5BREZ9ke0", image: "images/retour_vers_le_futur.jpg", acteurs: "Michael J. Fox, Christopher Lloyd", genres: [] },
    { titre: "retour_vers_le_futur_2", video: "https://www.youtube.com/watch?v=u72lyJirxGQ&t=14s", image: "images/retour_vers_le_futur_2.jpg", acteurs: "Michael J. Fox, Christopher Lloyd", genres: [] },
    { titre: "retour_vers_le_futur_3", video: "https://www.youtube.com/watch?v=Ugth9lQsKb0", image: "images/retour_vers_le_futur_3.jpg", acteurs: "Michael J. Fox, Christopher Lloyd", genres: [] },
    { titre: "rogue_one_star_wars", video: "https://www.youtube.com/watch?v=ox6Dsbvp7ng&t=35s", image: "images/rogue_on_star_wars.jpg", acteurs: "Felicity Jones, Diego Luna", genres: [] },
    { titre: "san_andreas", video: "https://www.youtube.com/watch?v=HGpwaIf3ZKk&t=40s", image: "images/san_andreas.jpg", acteurs: "Dwayne Johnson, Carla Gugino", genres: [] },
    { titre: "saw_1", video: "https://www.youtube.com/watch?v=8Swsh-up3iM&t=54s", image: "images/saw_1.jpg", acteurs: "Cary Elwes, Leigh Whannell", genres: [] },
    { titre: "saw_2", video: "https://www.youtube.com/watch?v=RzsCFIbUoVQ&t=21s", image: "images/saw_2.jpg", acteurs: "Donnie Wahlberg, Tobin Bell", genres: [] },
    { titre: "saw_3", video: "https://www.youtube.com/watch?v=91B113M4usE", image: "images/saw_3.jpg", acteurs: "Tobin Bell, Shawnee Smith", genres: [] },
    { titre: "saw_4", video: "https://www.youtube.com/watch?v=Qe8ZSX2NW0A", image: "images/saw_4.jpg", acteurs: "Tobin Bell, Costas Mandylor", genres: [] },
    { titre: "saw_5", video: "https://www.youtube.com/watch?v=3MiXFmlVPOY&t=44s", image: "images/saw_5.jpg", acteurs: "Tobin Bell, Costas Mandylor", genres: [] },
    { titre: "saw_6", video: "https://www.youtube.com/watch?v=4rv9dq2IQ-I", image: "images/saw_6.jpg", acteurs: "Tobin Bell, Costas Mandylor", genres: [] },
    { titre: "saw_7", video: "https://www.youtube.com/watch?v=oqE1tTFClh4", image: "images/saw_7.jpg", acteurs: "Tobin Bell, Costas Mandylor", genres: [] },
    { titre: "saw_8", video: "https://www.youtube.com/watch?v=QxiztUnTivE&t=39s", image: "images/saw_8.jpg", acteurs: "Tobin Bell, Costas Mandylor", genres: [] },
    { titre: "shang_chi", video: "https://www.youtube.com/watch?v=PD3rUCBFDlI&t=37s", image: "images/shang_chi.jpg", acteurs: "Simu Liu, Awkwafina", genres: [] },
    { titre: "shazam", video: "https://www.youtube.com/watch?v=KThUY2k_yW4", image: "images/shazam.jpg", acteurs: "Zachary Levi, Asher Angel", genres: [] },
    { titre: "shazam_2", video: "https://www.youtube.com/watch?v=VM5Hz-csjt8&t=4s", image: "images/shazam_2.jpg", acteurs: "Zachary Levi, Helen Mirren", genres: [] },
    { titre: "sinister", video: "https://www.youtube.com/watch?v=4sfzhzRAceE", image: "images/sinister.jpg", acteurs: "Ethan Hawke, Juliet Rylance", genres: [] },
    { titre: "sinister_2", video: "https://www.youtube.com/watch?v=DAVMVdX9AIE&t=33s", image: "images/sinister_2.jpg", acteurs: "James Ransone, Shannyn Sossamon", genres: [] },
    { titre: "sixieme_sens", video: "https://www.youtube.com/watch?v=HEd92ksuHNo", image: "images/sixieme_sens.jpg", acteurs: "Bruce Willis, Haley Joel Osment", genres: [] },
    { titre: "skyscraper", video: "https://www.youtube.com/watch?v=clKMwavvv6o", image: "images/skyscraper.jpg", acteurs: "Dwayne Johnson, Neve Campbell", genres: [] },
    { titre: "sonic", video: "https://www.youtube.com/watch?v=NCZTYdAP6w0", image: "images/sonic.jpg", acteurs: "Ben Schwartz, James Marsden (voice/live-action)", genres: [] },
    { titre: "sonic_2", video: "https://www.youtube.com/watch?v=SqH3-sCkZQw", image: "images/sonic_2.jpg", acteurs: "Ben Schwartz, James Marsden (voice/live-action)", genres: [] },
    { titre: "spider_man_far_from_home", video: "https://www.youtube.com/watch?v=FguIk-SEkWI&t=34s", image: "images/spider_man_far_from_home.jpg", acteurs: "Tom Holland, Zendaya", genres: [] },
    { titre: "spider_man_homecoming", video: "https://www.youtube.com/watch?v=Y8ErdqD5YPc", image: "images/spider_man_homecoming.jpg", acteurs: "Tom Holland, Michael Keaton", genres: [] },
    { titre: "spider_man_no_way_home", video: "https://www.youtube.com/watch?v=7w_w10HVa54", image: "images/spider_man_no_way_home.jpg", acteurs: "Tom Holland, Zendaya", genres: [] },
    { titre: "star_wars_1", video: "https://www.youtube.com/watch?v=0q-Q99DtNkw", image: "images/star_wars_1.jpg", acteurs: "Liam Neeson, Ewan McGregor", genres: [] },
    { titre: "star_wars_2", video: "https://www.youtube.com/watch?v=1D7DUNCHXkg", image: "images/star_wars_2.jpg", acteurs: "Ewan McGregor, Natalie Portman", genres: [] },
    { titre: "star_wars_3", video: "https://www.youtube.com/watch?v=t1qtvKYwTV0", image: "images/star_wars_3.jpg", acteurs: "Ewan McGregor, Hayden Christensen", genres: [] },
    { titre: "star_wars_4", video: "https://www.youtube.com/watch?v=PNyht4iTMX8", image: "images/star_wars_4.jpg", acteurs: "Mark Hamill, Harrison Ford", genres: [] },
    { titre: "star_wars_5", video: "https://www.youtube.com/watch?v=_y-xlGOuVaE", image: "images/star_wars_5.jpg", acteurs: "Mark Hamill, Harrison Ford", genres: [] },
    { titre: "star_wars_6", video: "https://www.youtube.com/watch?v=5QSEJx3R968", image: "images/star_wars_6.jpg", acteurs: "Mark Hamill, Harrison Ford", genres: [] },
    { titre: "star_wars_7", video: "https://www.youtube.com/watch?v=mH9Ygfs5avo&t=40s", image: "images/star_wars_7.jpg", acteurs: "Daisy Ridley, John Boyega", genres: [] },
    { titre: "star_wars_8", video: "https://www.youtube.com/watch?v=wY708Ky2SG8", image: "images/star_wars_8.jpg", acteurs: "Daisy Ridley, John Boyega", genres: [] },
    { titre: "star_wars_9", video: "https://www.youtube.com/watch?v=pHgwf2eMFnA&t=41s", image: "images/star_wars_9.jpg", acteurs: "Daisy Ridley, Adam Driver", genres: [] },
    { titre: "suicide_squad", video: "https://www.youtube.com/watch?v=XfboDbU3xnA", image: "images/suicide_squad.jpg", acteurs: "Will Smith, Margot Robbie", genres: [] },
    { titre: "super_mario", video: "https://www.youtube.com/watch?v=iwst-UZn3wM", image: "images/super_mario.jpg", acteurs: "Bob Hoskins, John Leguizamo", genres: [] },
    { titre: "taken_1", video: "https://www.youtube.com/watch?v=UX_71dbzJIw&t=22s", image: "images/taken_1.jpg", acteurs: "Liam Neeson, Maggie Grace", genres: [] },
    { titre: "taken_2", video: "https://www.youtube.com/watch?v=G_U2ZpXjpeg&t=26s", image: "images/taken_2.jpg", acteurs: "Liam Neeson, Maggie Grace", genres: [] },
    { titre: "taken_3", video: "https://www.youtube.com/watch?v=nSInrKvxIdI&t=42s", image: "images/taken_3.jpg", acteurs: "Liam Neeson, Forest Whitaker", genres: [] },
    { titre: "tenet", video: "https://www.youtube.com/watch?v=6UG5LJQNjts", image: "images/tenet.jpg", acteurs: "John David Washington, Robert Pattinson", genres: [] },
    { titre: "the_batman", video: "https://www.youtube.com/watch?v=hGQo1axtj60&t=34s", image: "images/the_batman.jpg", acteurs: "Robert Pattinson, Zoë Kravitz", genres: [] },
    { titre: "the_doors", video: "https://www.youtube.com/watch?v=z5X9rhbDtl4&t=33s", image: "images/the_doors.jpg", acteurs: "Val Kilmer, Meg Ryan", genres: [] },
    { titre: "the_island", video: "https://www.youtube.com/watch?v=EiBZakZa0TY&t=36s", image: "images/the_island.jpg", acteurs: "Ewan McGregor, Scarlett Johansson", genres: [] },
    { titre: "the_suicide_squad", video: "https://www.youtube.com/watch?v=lu4P7YmGgiE", image: "images/the_suicide_squad.jpg", acteurs: "Margot Robbie, Idris Elba", genres: [] },
    { titre: "thor_1", video: "https://www.youtube.com/watch?v=pzT3yeV9lT4&t=35s", image: "images/thor_1.jpg", acteurs: "Chris Hemsworth, Natalie Portman", genres: [] },
    { titre: "thor_le_monde_des_tenebres", video: "https://www.youtube.com/watch?v=WocFedghAHI", image: "images/thor_le_monde_des_tenebres.jpg", acteurs: "Chris Hemsworth, Natalie Portman", genres: [] },
    { titre: "thor_love_and_thunder", video: "https://www.youtube.com/watch?v=K8iHxGiPyZk", image: "images/thor_love_and_thunder.jpg", acteurs: "Chris Hemsworth, Natalie Portman", genres: [] },
    { titre: "thor_ragnarok", video: "https://www.youtube.com/watch?v=RtG6scyBIeM&t=42s", image: "images/thor_ragnarok.jpg", acteurs: "Chris Hemsworth, Tom Hiddleston", genres: [] },
    { titre: "titanic", video: "https://www.youtube.com/watch?v=Quf4qIkD3KY&t=31s", image: "images/titanic.jpg", acteurs: "Leonardo DiCaprio, Kate Winslet", genres: [] },
    { titre: "tomb_raider", video: "https://www.youtube.com/watch?v=UmXKhK9YKZg&t=35s", image: "images/tomb_raider.jpg", acteurs: "Angelina Jolie, Jon Voight", genres: [] },
    { titre: "top_gun", video: "https://www.youtube.com/watch?v=i8sEGppZX-s", image: "images/top_gun.jpg", acteurs: "Tom Cruise, Kelly McGillis", genres: [] },
    { titre: "transformers_1", video: "https://www.youtube.com/watch?v=_XKAU3tYO9M&t=11s", image: "images/transformers_1.jpg", acteurs: "Shia LaBeouf, Megan Fox", genres: [] },
    { titre: "transformers_2", video: "https://www.youtube.com/watch?v=u9uUVkYB6Aw&t=13s", image: "images/transformers_2.jpg", acteurs: "Shia LaBeouf, Megan Fox", genres: [] },
    { titre: "transformers_3", video: "https://www.youtube.com/watch?v=7-ZBYb2poUM&t=12s", image: "images/transformers_3.jpg", acteurs: "Shia LaBeouf, Rosie Huntington-Whiteley", genres: [] },
    { titre: "transformers_4", video: "https://www.youtube.com/watch?v=O3cpckQmmk8&t=60s", image: "images/transformers_4.jpg", acteurs: "Mark Wahlberg, Stanley Tucci", genres: [] },
    { titre: "transformers_5", video: "https://www.youtube.com/watch?v=IsUacT2oFwU", image: "images/transformers_5.jpg", acteurs: "Mark Wahlberg, Anthony Hopkins", genres: [] },
    { titre: "twilight_1", video: "https://www.youtube.com/watch?v=xzO_Iiwt4b4", image: "images/twilight_1.jpg", acteurs: "Kristen Stewart, Robert Pattinson", genres: [] },
    { titre: "twilight_2", video: "https://www.youtube.com/watch?v=ShHNEvFPtvc", image: "images/twilight_2.jpg", acteurs: "Kristen Stewart, Robert Pattinson", genres: [] },
    { titre: "twilight_3", video: "https://www.youtube.com/watch?v=yi4xJGebtuk", image: "images/twilight_3.jpg", acteurs: "Kristen Stewart, Robert Pattinson", genres: [] },
    { titre: "twilight_4", video: "https://www.youtube.com/watch?v=_jWriOZlsnw&t=50s", image: "images/twilight_4.webp", acteurs: "Kristen Stewart, Robert Pattinson", genres: [] },
    { titre: "twilight_5", video: "https://www.youtube.com/watch?v=CjdPAg-gyFE&t=43s", image: "images/twilight_5.jpg", acteurs: "Kristen Stewart, Robert Pattinson", genres: [] },
    { titre: "un_hologram_pour_le_roi", video: "https://www.youtube.com/watch?v=TLpl17kCevA&t=42s", image: "images/un_hologram_pour_le_roi.jpg", acteurs: "Tom Hanks, Alexander Black", genres: [] },
    { titre: "underworld_1", video: "https://www.youtube.com/watch?v=2_IoL7g5Ub8&t=21s", image: "images/underworld_1.jpg", acteurs: "Kate Beckinsale, Scott Speedman", genres: [] },
    { titre: "underworld_2", video: "https://www.youtube.com/watch?v=v86oFYYz3Bg&t=40s", image: "images/underworld_2.jpg", acteurs: "Kate Beckinsale, Scott Speedman", genres: [] },
    { titre: "underworld_3", video: "https://www.youtube.com/watch?v=Ebp9UDnzE7c&t=28s", image: "images/underworld_3.jpg", acteurs: "Michael Sheen, Bill Nighy", genres: [] },
    { titre: "underworld_4", video: "https://www.youtube.com/watch?v=76U14o8QeXk", image: "images/underworld_4.jpg", acteurs: "Kate Beckinsale, Stephen Rea", genres: [] },
    { titre: "underworld_5", video: "https://www.youtube.com/watch?v=a61vd2UpaDg", image: "images/underworld_5.jpg", acteurs: "Kate Beckinsale, Theo James", genres: [] },
    { titre: "very_bad_trip_1", video: "https://www.youtube.com/watch?v=hHqR9Tq16_E&t=23s", image: "images/very_bad_trip_1.jpg", acteurs: "Bradley Cooper, Ed Helms", genres: [] },
    { titre: "very_bad_trip_2", video: "https://www.youtube.com/watch?v=DFw9AlqUbYQ&t=25s", image: "images/very_bad_trip_2.jpg", acteurs: "Bradley Cooper, Ed Helms", genres: [] },
    { titre: "very_bad_trip_3", video: "https://www.youtube.com/watch?v=ibq2kS7NRaU&t=29s", image: "images/very_bad_trip_3.jpg", acteurs: "Bradley Cooper, Ed Helms", genres: [] },
    { titre: "volte_face", video: "https://www.youtube.com/watch?v=K-gncct2TX8", image: "images/volte_face.jpg", acteurs: "John Travolta, Nicolas Cage", genres: [] },
    { titre: "vox_lux", video: "https://www.youtube.com/watch?v=fMCYE9hKP68&t=29s", image: "images/vox_lux.jpg", acteurs: "Natalie Portman, Jude Law", genres: [] },
    { titre: "wolverine", video: "https://www.youtube.com/watch?v=WKrknCZIj2Q", image: "images/wolverine.jpg", acteurs: "Hugh Jackman, Tao Okamoto", genres: [] },
    { titre: "wonder_woman", video: "https://www.youtube.com/watch?v=CWe308Fpywg", image: "images/wonder_woman.jpg", acteurs: "Gal Gadot, Chris Pine", genres: [] },
    { titre: "wonder_woman_1984", video: "https://www.youtube.com/watch?v=rhlHVvmVf04", image: "images/wonder_woman_1984.jpg", acteurs: "Gal Gadot, Chris Pine", genres: [] },
    { titre: "xmen_1", video: "https://www.youtube.com/watch?v=QLtF7ZmXfjw", image: "images/xmen_1.jpg", acteurs: "Hugh Jackman, Patrick Stewart", genres: [] },
    { titre: "xmen_2", video: "https://www.youtube.com/watch?v=WmzABBFM6CY&t=34s", image: "images/xmen_2.jpg", acteurs: "Hugh Jackman, Halle Berry", genres: [] },
    { titre: "xmen_3", video: "https://www.youtube.com/watch?v=dE5rzrBKfPc&t=14s", image: "images/xmen_3.jpg", acteurs: "Hugh Jackman, Halle Berry", genres: [] },
    { titre: "xmen_apocalyspse", video: "https://www.youtube.com/watch?v=8chgx3qqZNA&t=9s", image: "images/xmen_apocalyspse.jpg", acteurs: "James McAvoy, Michael Fassbender", genres: [] },
    { titre: "xmen_dark_phoenix", video: "https://www.youtube.com/watch?v=11_xxw6VZv8&t=2s", image: "images/xmen_dark_phoenix.jpg", acteurs: "Sophie Turner, James McAvoy", genres: [] },
    { titre: "xmen_days_of_futur_past", video: "https://www.youtube.com/watch?v=6esGeXis858", image: "images/xmen_days_of_futur_past.jpg", acteurs: "Hugh Jackman, James McAvoy", genres: [] },
    { titre: "xmen_le_commencement", video: "https://www.youtube.com/watch?v=tT8oQT8ILpY&t=30s", image: "images/xmen_le_commencement.jpg", acteurs: "James McAvoy, Michael Fassbender", genres: [] },
    { titre: "xmen_origins", video: "https://www.youtube.com/watch?v=yawHvdrZrcs&t=35s", image: "images/xmen_origins.jpg", acteurs: "Hugh Jackman, Liev Schreiber", genres: [] }
];